### ISSUE TITLE
Strange race condition / undefined behaviour in the tests with the updated audio_mixing branch.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pitivi/gst-editing-services#25]
The test has been commented out for now, it's at line 263 in tests/check/ges/layer.c.
If we want to keep the set_priority API we need to port it to the new behaviour.

If that line is uncommented, a g_sequence assertion will pop once in a while.

reminder : the audio_mixing branch is here : 
https://github.com/MathieuDuponchelle/PitiviGes/tree/audio_mixing

**Comment by thiblahute** [comment]
@MathieuDuponchelle  Still relevant?

**Comment by thiblahute** [comment]
No
