### ISSUE TITLE
Review of video mixing.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pitivi/gst-editing-services#26]
The branch is there : 
https://github.com/MathieuDuponchelle/PitiviGes/commits/video_mixing

and awaiting review

**Comment by thiblahute** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/cf2698a97e3fe2f9c70ad60fd28bf37a09c21b37

**Comment by thiblahute** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/c1cfb81b15258c3cb27643456dadeb1b441d608f

**Comment by thiblahute** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/939bf718fe8c290750dbae6156813bda5f7f7006

**Comment by MathieuDuponchelle** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/b2cadbac585441d94d00286bfe197c11bfe5caf1

done.

**Comment by thiblahute** [comment]
You should also check if videomixer is present in ges_init and WARN the user/disable the feature if not I think.

**Comment by thiblahute** [comment]
From cbdd87151225f1ea80c7084606e8ccc255e12934 to 01a5963dc73123305b2793199ee5d6af5bc3b317
- [x] It should should be called smart-video-mixer.c I think
- [x] Great news :D
- [x] Really?
- [x] Not sure it is a WARNING here
- [x] I though it was 0.75 the real number....
- [x] We really want the debugging to be ges\* filtrable here! Either you remove that,
- [x] or you make in inside the GES namespace
- [x] Not so dummy....
- [x] Sure you do not want to set x-y-z-alpha here?!
- [x] Why don't you take the lock before and unlock after that whole switch? (would be
- [x] the same thing in term of execution)
- [ ] I think you include it in the .c also...
- [ ] OOPS...
  
  diff --git a/ges/ges-smart-mixer.c b/ges/ges-smart-mixer.c

It should should be called smart-video-mixer.c I think

```
@@ -0,0 +1,237 @@
+/* -*- Mode: C; indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4 -*-  */
+/*
+ * gst-editing-services
+ *
+ * Copyright (C) 2013 Thibault Saunier <tsaunier@gnome.org>
```

Great news :D

```
+#include <gst/audio/audio.h>
```

Really?

```
+static GstPadProbeReturn
+parse_metadata (GstPad * mixer_pad, GstPadProbeInfo * info, gpointer unused)
+{
+  GstFramePositionnerMeta *meta;
+
+  meta =
+      (GstFramePositionnerMeta *) gst_buffer_get_meta ((GstBuffer *) info->data,
+      gst_frame_positionner_meta_api_get_type ());
+
+  if (!meta) {
+    GST_WARNING ("The current source should use a framepositionner");
```

Not sure it is a WARNING here

```
+/****************************************************
+ *              GstElement vmetods                  *
+ ****************************************************/
+static GstPad *
+_request_new_pad (GstElement * element, GstPadTemplate * templ,
+    const gchar * name, const GstCaps * caps)
+{
+  GstPad *videoconvert_srcpad, *videoconvert_sinkpad, *tmpghost;
+  PadInfos *infos = g_slice_new0 (PadInfos);
+  GESSmartMixer *self = GES_SMART_MIXER (element);
+  GstPad *ghost;
+  GstElement *videoconvert;
+
+  infos->mixer_pad = gst_element_request_pad (self->mixer,
+      gst_element_class_get_pad_template (GST_ELEMENT_GET_CLASS (self->mixer),
+          "sink_%u"), NULL, NULL);
+
+  g_object_set (G_OBJECT (infos->mixer_pad), "alpha", 0.5, NULL);
```

I though it was 0.75 the real number....

```
+
+GST_DEBUG_CATEGORY_STATIC (gst_frame_positionner_debug_category);
+#define GST_CAT_DEFAULT gst_frame_positionner_debug_category
+
```

We really want the debugging to be ges\* filtrable here! Either you remove that,
or you make in inside the GES namespace

```
+      "frame positionner", "Metadata",
+      "This dummy element provides with tagging facilities",
```

Not so dummy....

```
+gst_frame_positionner_init (GstFramePositionner * framepositionner)
+{
+}
```

Sure you do not want to set x-y-z-alpha here?!

```
+  switch (property_id) {
+    case PROP_ALPHA:
+      GST_OBJECT_LOCK (framepositionner);
+      framepositionner->alpha = g_value_get_double (value);
+      GST_OBJECT_UNLOCK (framepositionner);
+      break;
+    case PROP_POSX:
+      GST_OBJECT_LOCK (framepositionner);
+      framepositionner->posx = g_value_get_int (value);
+      GST_OBJECT_UNLOCK (framepositionner);
+      break;
+    case PROP_POSY:
+      GST_OBJECT_LOCK (framepositionner);
+      framepositionner->posy = g_value_get_int (value);
+      GST_OBJECT_UNLOCK (framepositionner);
+      break;
+    case PROP_ZORDER:
+      GST_OBJECT_LOCK (framepositionner);
+      framepositionner->zorder = g_value_get_uint (value);
+      GST_OBJECT_UNLOCK (framepositionner);
+      break;
```

Why don't you take the lock before and unlock after that whole switch? (would be
the same thing in term of execution)

```
+#define _GST_FRAME_POSITIONNER_H_
+
+#include <gst/base/gstbasetransform.h>
```

I think you include it in the .c also...

 GST_END_TEST;

```
+static gboolean
+print_position (GstElement * pipeline)
+{
+  gint64 pos;
+
+  gst_element_query_position (pipeline, GST_FORMAT_TIME, &pos);
+  GST_ERROR ("position : %" GST_TIME_FORMAT, GST_TIME_ARGS (pos));
```

Oops

**Comment by MathieuDuponchelle** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/d1e51337aab0b7ecf7c3d5efd336b3ef611f1353

**Comment by thiblahute** [comment]
Impressive commit :P

**Comment by MathieuDuponchelle** [comment]
I know I know, so much time spent on that one.

**Comment by MathieuDuponchelle** [comment]
https://github.com/MathieuDuponchelle/PitiviGes/commit/c752bde6ea3650f5fa05b90b8389bac1b8b8ccb1
https://github.com/MathieuDuponchelle/PitiviGes/commit/37c68a79b8448dbdc931dd5f6fee2883d04f98b8
https://github.com/MathieuDuponchelle/PitiviGes/commit/17fc842c4730c2a89cea48cb1545d8d63ed682bd
https://github.com/MathieuDuponchelle/PitiviGes/commit/cbd2f0762a66a90f69980335b2327ecb355a0dfa
https://github.com/MathieuDuponchelle/PitiviGes/commit/af8bcdf18154304f455202c106b399fda9682f5e

**Comment by thiblahute** [comment]
This is now merged, but I am not closing until you write some documentation about the new feature...

setting as Work needed

**Comment by MathieuDuponchelle** [comment]
Closing because merged
