### ISSUE TITLE
Implement proper videorate property rate

### ISSUE THREAD

**Issue by jojva** [pitivi/gst-editing-services#28]
Latest commit: jojva/gst-plugins-base@fd9eb512dfac21263dcc35c949fbaae7fc4e169a
Previous: jojva/gst-plugins-base@1a38e23287e0c624a9e953717f413fff4bdfc27a

What works now (tested with gst-launch): 
- Accelerating a video (e.g. rate = 2), pipeline receives EOS and stops right after all buffers have been played.
- Slowing down a video (e.g. rate = .5), same thing. The player seems to display the whole video. I tried with the ball pattern and some random big bang theory episode extract

What I don't know yet : seeking

**Comment by MathieuDuponchelle** [comment]
This looks fine to me except for the comments I made. You should really look at pitch for everything related to that kind of property, and that should provide you answer about seeking I think.
The next step would now be to write a test in either gnl or GES, and see how you can integrate that work.
I added various helpers functions in ges-uri-source.c here : https://github.com/MathieuDuponchelle/PitiviGes/tree/video_mixing , I think we could push the bits relevant to you on master.

**Comment by jojva** [comment]
I just pushed the fix, commit SHA is updated in my first post. I'll squash the commits later.
I added:
query position and duration handling
sync_values()
update_duration()

**Comment by thiblahute** [comment]
We are on it, and have a bug for it already
