### ISSUE TITLE
Annotation fixes for request_sync.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pitivi/gst-editing-services#29]
https://github.com/MathieuDuponchelle/PitiviGes/commit/4e1bdd78aba1a162a8c40ba63ac50b08e57dbed9

**Comment by thiblahute** [comment]
commit 1d00f45f4f0c4a236b30a104aa382066315b1d10
Author: Mathieu Duponchelle mathieu.duponchelle@epitech.eu
Date:   Tue Apr 30 19:16:10 2013 +0200

```
ges-uri-asset.c: Fix ges_uri_asset_request_sync annotations.
```
