### ISSUE TITLE
GESLayer add_asset ignores in-point

### ISSUE THREAD

**Issue by lubosz** [pitivi/gst-editing-services#33]
The in-point is ignored in this example

``` python
#!/usr/bin/python

from gi.repository import GES, Gst, GLib

# File URL http://download.blender.org/peach/trailer/trailer_400p.ogg

videoFile = "file:///home/bmonkey/workspace/ges/data/trailer_400p.ogg"

def quit(bar):
  GLib.MainLoop.quit(bar)
  exit()

def simple():
  Gst.init(None)
  GES.init()

  timeline = GES.Timeline.new_audio_video()

  asset = GES.UriClipAsset.request_sync(videoFile)

  layer = GES.Layer()
  timeline.add_layer(layer)
  layer.add_asset(asset, 0, 20 * Gst.SECOND, 3 * Gst.SECOND, asset.get_supported_formats())

  pipeline = GES.TimelinePipeline()
  pipeline.add_timeline(timeline)
  pipeline.set_state(Gst.State.PLAYING)

  mainLoop = GLib.MainLoop.new(None, False)
  GLib.timeout_add_seconds(3, quit, mainLoop)
  GLib.MainLoop().run()

simple()
```

**Comment by lubosz** [comment]
start also is ignored

**Comment by thiblahute** [comment]
You are forgetting to commit the timeline:

```
layer.add_asset(asset, 0, 20 * Gst.SECOND, 3 * Gst.SECOND, asset.get_supported_formats())
timeline.commit()
```

It is the new API that makes it possible to change the timeline content while playing, but it means that each time you want  your changes to be taken into account, you need to call this method.

Please close this bug when you confirm that it is the issue (I checked quickly myself, and it seems to be)

**Comment by lubosz** [comment]
timeline.commit() solves this problem. thanks. so it's not a bug, but API misuse.
strangely the video is interlaced now, but this is another issue.
http://i.imgur.com/9SWl1m9.png
http://i.imgur.com/FxYmymx.png
