### ISSUE TITLE
Add layer mixing tests in the integration test suite.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pitivi/gst-editing-services#42]
https://gist.github.com/MathieuDuponchelle/5736992#file-mixit-py

This is a python example of how the property is used.

I don't have much ideas about what to actually test for now, apart from the standard checks for EOS and rendered file length.

Ideas welcome :)

**Comment by vliaskov** [comment]
A first test is here, comments welcome:
https://github.com/vliaskov/PitiviGes/commit/cbde04fbf642ba2b8b76d650095318a788e7b5cc

**Comment by vliaskov** [comment]
@MathieuDuponchelle  and @thiblahute let me know if you have any suggestions for improving the above test.

**Comment by thiblahute** [comment]
Merged, thanks :)
