### ISSUE TITLE
Make GES compatible with videorate

### ISSUE THREAD

**Issue by jojva** [pitivi/gst-editing-services#44]
So this commit has already been done to add videorate to the bin : a0bd3cf51cc4213c8e738ede6cee8428071ba312

Now we want to be able to change its rate property without breaking everything. Here's a proposed patch to update duration of the clip : jojva/gst-editing-services@13973bf440ad3fe14d59a5d50fc22a67ab307ac6

**Comment by thiblahute** [comment]
It looks good to me
