### ISSUE TITLE
GES Project's "new" method says I can't change the URI afterwards

### ISSUE THREAD

**Issue by nekohayo** [pitivi/gst-editing-services#50]
Quoting the docs: "If you then save the project to other locations, it will never be updated again and the first valid URI is the URI it will keep refering to."

This does not make any sense. The save method should update the URI at least.

Otherwise we can't replace pitivi's self.current.uri variable by GES'.

**Comment by thiblahute** [comment]
In GES terms a project is an asset and this asset is defined by its URI, so if you want to save it to another directory you have to create a new GES asset as it becomes a new asset.

In ptv we sublcassed it so we have the behaviour we expect, and we do not want to replace pitivi current.uri by GES as this is what that subclass is meant to do.
