### ISSUE TITLE
On my 32 bit system, test-snapping fails

### ISSUE THREAD

**Issue by jojva** [pitivi/gst-editing-services#55]
test-snapping from timelineedition.c fails on reading:
g_object_set (clip1, "duration", 46, NULL);
and another similar line.
(Very) weird error: http://pastebin.com/qLxZeTRj
Fix is here: jojva@5f443bed296aeef2669f9aa89a64e45179e66366

**Comment by thiblahute** [comment]
On Fri, 2013-09-13 at 19:24 -0700, Joris Valette wrote:

> test-snapping from timelineedition.c fails on reading:
> g_object_set (clip1, "duration", 46, NULL);
> and another similar line.
> (Very) weird error: http://pastebin.com/qLxZeTRj
> Fix is here: jojva@5f443be

Indeed the error message is interesting! I have already seen this kind
of weirdness, but that message was specialy unanderstandable!

**Comment by thiblahute** [comment]
pushed
