### ISSUE TITLE
Make test_project_add_keyframes compatible with control binding update

### ISSUE THREAD

**Issue by jojva** [pitivi/gst-editing-services#56]
From #pitivi: 
"<jojva> hi, i'm in need for someone's point of view on a bug. Since i've changed the formatter to include children-properties like posx, posy, rate, width and height etc., these are automatically saved and loaded via xyz.xges.
<jojva> now test_project_add_keyframes fails because, when the rate property is parsed, it is then set onto videorate element, which calls a callback which updates track-element's duration and max-duration.
<jojva> But, even though the rate is 1, updating the duration automatically updates the control-bindings
<jojva> So the timed values that are set in the test become wrong.
<jojva> I guess that's because the timed values ts are on ts 0; 5; and 10, but the default duration is smaller
<jojva> Should I get these numbers smaller ?
<jojva> like 0; 0.05 and 0.1"

Actually, the _default_ duration is 1 \* GST_SECOND. So I changed the values to 0; 0.5 and 1 GST_SECOND. That way, even if keyframes are recomputed by interpolation, they keep their original values.
This patch depends on the default duration being 1, if that's ugly maybe a better solution is to set the duration (and max_duration ?) of the track-element to some fixed value.

Patch: jojva@3d443f45c294a58f1f3890ab550ef58585159585

**Comment by MathieuDuponchelle** [comment]
I don't understand why it is needed, the default duration of what ? Could you please explain what exactly happends in a step by step way ? I don't have enough context here to judge if it is right.
