### ISSUE TITLE
ProRes files make the pipeline explode

### ISSUE THREAD

**Issue by nekohayo** [pitivi/gst-editing-services#57]
Grab this sample file here (you are welcome to use it as part of your integration tests):
http://jeff.ecchi.ca/public/PRORES%20SAMPLE%20FOR%20DANNY.mov

Insert it into a blank Pitivi timeline, and you will get thousands (endless) error messages:

```
ERROR 15:08:06 pipeline             _busMessageCb: error from <__main__.GstQTDemux object at 0x5326fa0 (GstQTDemux at 0x45319d0)>: GStreamer encountered a general stream error. (qtdemux.c(4394): gst_qtdemux_loop (): /pitivi+utils+pipeline+Pipeline:pitivi+utils+pipeline+pipeline1/GESTimeline:gestimeline1/GESVideoTrack:gesvideotrack1/GnlComposition:gnlcomposition2/GnlSource:gnlsource0/GstBin:videosrcbin/GstURIDecodeBin:uridecodebin2/GstDecodeBin:decodebin103/GstQTDemux:qtdemux99:
streaming stopped, reason not-linked) (../pitivi/pitivi/utils/pipeline.py:433)
```

**Comment by thiblahute** [comment]
Does it properly work with a simple gst player?

**Comment by MathieuDuponchelle** [comment]
gst-launch-1.0 uridecodebin uri=file:///home/meh/Videos/prores.mov ! videoconvert ! autovideosink works, errors in pitivi indeed. I confirm the bug.

**Comment by thiblahute** [comment]
Was in pitivi anyway, should we test again there.
